const colors = {
  light: {
    text: "#0D1B2A",
    tint: "#0EA5E9",
    background: "#F0F7FF",
    foreground: "#0D1B2A",
    card: "#FFFFFF",
    cardForeground: "#0D1B2A",
    primary: "#0EA5E9",
    primaryForeground: "#FFFFFF",
    secondary: "#E0F2FE",
    secondaryForeground: "#0369A1",
    muted: "#E8F4FD",
    mutedForeground: "#64748B",
    accent: "#10B981",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DBEAFE",
    input: "#E0F2FE",
  },
  dark: {
    text: "#E2EAF4",
    tint: "#38BDF8",
    background: "#070D1A",
    foreground: "#E2EAF4",
    card: "#0F1A2E",
    cardForeground: "#E2EAF4",
    primary: "#38BDF8",
    primaryForeground: "#0D1B2A",
    secondary: "#1E3A5F",
    secondaryForeground: "#93C5FD",
    muted: "#152035",
    mutedForeground: "#8B9BAD",
    accent: "#10B981",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A5F",
    input: "#1E3A5F",
  },
  radius: 16,
};

export default colors;
