uploads = []

[[generated]]
id = "rTkSM_Y1jvkL-1H3b2sDa"
uri = "file://artifacts/hydrapulse/assets/images/icon.png"
type = "image"
title = "hydrapulse app icon"

[[generated]]
id = "rd8EaOG8VIdle5U1qLbVw"
uri = "file://artifacts/mockup-sandbox/public/images/geyser.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_EUtptsuv2Ji0vRO9L1yh"
uri = "file://artifacts/mockup-sandbox/public/images/drinking-water.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-QryfOnD8rnDQ-sSMjycs"
uri = "file://artifacts/hydrapulse/assets/images/adaptive-icon.png"
type = "image"
title = "hydrapulse adaptive icon"

[[generated]]
id = "kVi4GGQGyaqXntollOmaW"
uri = "file://artifacts/hydrapulse/assets/images/splash-icon.png"
type = "image"
title = "hydrapulse splash screen clean"

[[outputs]]
id = "k4S_BXshPRmJhYieADyDO"
uri = "file://attached_assets/hydrapulse-dev-qr.png"
type = "image"
title = "HydraPulse Dev Client QR Code"
