// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/streak-celebration/Preview.tsx": () => import("../components/mockups/streak-celebration/Preview.tsx"),
  "./components/mockups/today-banner/FullArc.tsx": () => import("../components/mockups/today-banner/FullArc.tsx"),
  "./components/mockups/today-banner/GoalFirst.tsx": () => import("../components/mockups/today-banner/GoalFirst.tsx"),
  "./components/mockups/today-banner/SplitHero.tsx": () => import("../components/mockups/today-banner/SplitHero.tsx")
};
